server:
  port: 80

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    preferIpAddress: true

spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://localhost:9091/
    locator:
      discovery:
        enabled: true
    sender:
      type: web

zuul:
  ignoredPatterns: /me, /events**
  routes:
    ui-service:
      path: /**
      serviceId: ui-service
      stripPrefix: false

security:
  oauth2:
    client:
      clientId: ${GOOGLE_CLIENT_ID}
      clientSecret: ${GOOGLE_CLIENT_SECRET}
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true

messaging:
  gpsEventsSender:
    exchangeName: mobile
    bindingName: track
    queueName: mobile.track


---
spring:
  profiles: production

  rabbitmq:
    host: 10.24.2.5

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.27.245.43:8080/eureka/


---
spring:
  profiles: test

messaging:
  gpsEventsSender:
    exchangeName: mobileTest
    bindingName: trackTest
    queueName: mobileTest.trackTest


---
spring:
  profiles: debug

logging:
  level:
    pl.edu.agh.iet.dts: DEBUG
