server:
  port: 80

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    preferIpAddress: true

zuul:
  routes:
    ui-service:
      path: /**
      serviceId: ui-service
      stripPrefix: true
