server:
  port: 9091

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    preferIpAddress: true


---
spring:
  profiles: production

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_IP}:8080/eureka/
