server:
  port: 8081

spring:
  resources:
    staticLocations: classpath:pl/edu/agh/iet/dts/ui/static/

  data:
    mongodb:
      host: localhost
      database: uiService

  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: http://localhost:9091/
    locator:
      discovery:
        enabled: true
    sender:
      type: web

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    preferIpAddress: true

messaging:
  aggregationTaskSender:
    exchangeName: web
    bindingName: task
    queueName: web.task
  aggregatedDataReceiver:
    exchangeName: web
    bindingName: aggregated
    queueName: web.aggregated

scheduler:
  threads:
    poolSize: 5


---
spring:
  profiles: production

  data:
    mongodb:
      host: ${MONGODB_IP}

  rabbitmq:
    host: ${RABBITMQ_IP}

  zipkin:
    baseUrl: http://${ZIPKIN_IP}:9091/

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_IP}:8080/eureka/


---
spring:
  profiles: test

  data:
    mongodb:
      database: uiService-test

messaging:
  aggregationTaskSender:
    exchangeName: webTest
    bindingName: taskTest
    queueName: webTest.taskTest
  aggregatedDataReceiver:
    exchangeName: webTest
    bindingName: aggregatedTest
    queueName: webTest.aggregatedTest


---
spring:
  profiles: debug

logging:
  level:
    pl.edu.agh.iet.dts: DEBUG
