server:
  port: 8081

spring:
  resources:
    staticLocations: classpath:pl/edu/agh/iet/dts/ui/static/

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    preferIpAddress: true
