server:
  port: 8081

spring:
  resources:
    staticLocations: classpath:pl/edu/agh/iet/dts/ui/static/
  data:
    mongodb:
      host: localhost
      port: 27017
      database: devices-tracking-system

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    preferIpAddress: true

scheduler:
  threads:
    poolSize: 5
