server:
  port: 8081

spring:
  resources:
    staticLocations: classpath:pl/edu/agh/iet/dts/ui/static/
  data:
    mongodb:
      host: localhost
      port: 27017
      database: uiService

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    preferIpAddress: true

messaging:
  aggregationTaskSender:
    exchangeName: web
    bindingName: task
    queueName: web.task
  aggregatedDataReceiver:
    exchangeName: web
    bindingName: aggregated
    queueName: web.aggregated

scheduler:
  threads:
    poolSize: 5
